apiVersion: ENC[AES256_GCM,data:k3g=,iv:tu6hs7tZMZZumh0bDTfw+pP4g3Fur/sBbzE+nBcqJT8=,tag:FxyXVJ9RW9TOvzDykTc//A==,type:str]
kind: ENC[AES256_GCM,data:ebl874Wz,iv:NdOdygUOeEK5hKyYisgdoyZRWZCLAOFO0LfZegUhvxY=,tag:PWxalJGeb4W37JA1b6pECg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tnRCDjmxukd9Arw=,iv:pMILsq5LFfQI0379GVbFNzcsZng2STginRGpwXDcyR8=,tag:q2cRx/yolHjy3zn5FehMcA==,type:str]
    namespace: ENC[AES256_GCM,data:3Jb0VImUwoUgqA==,iv:3x+4XkWxt26hUzO0dziih2pvDwAnQV7o2fap0zI7h9g=,tag:hxqgAwIzTOF5v2UUtQMqjw==,type:str]
type: ENC[AES256_GCM,data:/5izmMut,iv:ZsOBnlPctMQpTVrD+3wpHHL4CQRse2hTZbqsKnJxqIQ=,tag:xjUBABCLxrU7/6RosbjSOg==,type:str]
stringData:
    BOT_TOKEN: ENC[AES256_GCM,data:OgL1HEu34IGMrNoEko43kNdJ6kgJ3TQG1hnEdQ9Umpk7xZEYy9xpRrMUUQ4sxg==,iv:qS75rBa5cwG+s+O6IqFZ5Q6Wf1ZVYHv/Rwd8vl8sPEk=,tag:442INE7eDGgkpRVYFnkzlw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Ky2wjrlJCQU=,iv:RB0fuVNJNk177v1k4Ocb2vPGpr5QwsDiC1UmHho6FfI=,tag:TGfIDSTdSxOINCLWt32nCA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:WvLGxa/nGLk=,iv:hvwdrN6wMAbsQ4G7tBLz8bEEERRzUOGglRu5MwT8oYo=,tag:IUu8FJaLTJL5PSjflM469w==,type:int]
    POSTGRES_DB: ENC[AES256_GCM,data:ufhcHMm168a7TGl7vKy6c7LR,iv:uQxvC67xGbX2Y24d1PuVB1MC+U6mhrgnlp/7DkKQqGw=,tag:HXTWkscXLockWpOJ3Otsdw==,type:str]
    COMPETITION_START_DATE: ENC[AES256_GCM,data:Ece6I5toOE4mBkvA+27HNw60330=,iv:ce/Hqypfmc7QRkDCEPd9Adlz3fjlk3+i+Qd33NeCIK8=,tag:XWuKZj8N7J5+VlG1D8bRCQ==,type:time]
    COMPETITION_END_DATE: ENC[AES256_GCM,data:EDfj/kAMrQ8xgM3SLKdp4tvJgk8=,iv:d7V0jjny66T2Bbynxjeudrt3rFD8g5NsNsXf4aw4l7Y=,tag:im2EON/KENXwb1k/e9G27w==,type:time]
    MB_ENCRYPTION_SECRET_KEY: ENC[AES256_GCM,data:l2r3b+yWXCCt9a6Goy9bxLjsw5Pg/yWlC4/ZKdoFqc7GLv1wZAQ2vrJws3k=,iv:F1WyZIrM0M5fXUFB4bY0fm+4NGYu9u3ecY5/7QMiSJw=,tag:gApyC7yEttkWmtmSEll/pw==,type:str]
sops:
    age:
        - recipient: age18jj73k865cqfaew3pmshqrqwfmns78jj8ppd8kj8m6lxd8cn63vq0kaa6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3T0x6Tkg1Q2FmeEVYOHIx
            bHlUYUl3K2hNa0FxQkY4UkowQlkzb1YvNW1NCjlYVjBta01USHpkRlpGOEsrRm5X
            LzN2ODFESFdkc1F6OXZ6SndEV1RxNWMKLS0tIDZqNUtkYWMxeGtCODZEZWNkeTJk
            aVc4R2tPRzR6aXR0alFybVhjZXFQZ1UKAAvWB59TqDz8coNN8N/NZrY9oseuqRyl
            UHMlpwi1ZTSgf/blQVin9BLQ3TdGVIpWTnIUXdaOQNFucQDkbQQ3Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T13:50:22Z"
    mac: ENC[AES256_GCM,data:V+8qY8qknadkAG1uMw6Xh4WXjRbSaJF3ICRKvIksLybNyfncTnE2RyaQUjAcGHl+WfyKa9y/Wa/d3rEdhdhyAevLrLeUrUhTeP2MZ7iXoM1QMvhKNzVjI17p2sCJ/G/eN7Hshj8uT1hcfo0gLv8wV3xCdzXBuvOSaxlxS57sYpA=,iv:ZlXIISDE+6HOJOf3mydXNcZ7safBLx5fGJVdl6umZm8=,tag:yE/1kN6XBp8safSBt/Fn/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
